# Generated by Django 6.0.6 on 2026-07-03 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorecards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='chorecard',
            old_name='description',
            new_name='checklist',
        ),
        migrations.RemoveField(
            model_name='chorecard',
            name='assignee',
        ),
        migrations.AddField(
            model_name='chorecard',
            name='assignee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
