# Generated by Django 6.0.6 on 2026-07-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorecards', '0002_rename_description_chorecard_checklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chorecard',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chorecard',
            name='difficulty_weight',
            field=models.PositiveBigIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='chorecard',
            name='status',
            field=models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('overdue', 'Overdue'), ('completed', 'Completed')], max_length=20, null=True),
        ),
    ]
