# Generated by Django 6.0.6 on 2026-07-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorecards', '0003_alter_chorecard_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chorecard',
            name='difficulty_weight',
            field=models.PositiveBigIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
    ]
