# Generated by Django 6.0.6 on 2026-07-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorecards', '0004_alter_chorecard_difficulty_weight'),
        ('members', '0002_member_duplication_check_for_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chorecard',
            old_name='household',
            new_name='householdgroup',
        ),
        migrations.AddField(
            model_name='chorecard',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chorecard',
            name='assignee',
            field=models.ManyToManyField(to='members.member'),
        ),
        migrations.AlterField(
            model_name='chorecard',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chorecard',
            name='difficulty_weight',
            field=models.PositiveBigIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='chorecard',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
