# Generated by Django 6.0.6 on 2026-07-03 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('householdgroups', '0002_householdgroup_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Group Owner'), ('member', 'Member')], max_length=20)),
                ('contribution', models.PositiveIntegerField(default=0)),
                ('penalty', models.PositiveIntegerField(default=0)),
                ('householdgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='householdgroups.householdgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
