# Generated by Django 6.0.6 on 2026-07-23 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('householdgroups', '0003_alter_householdgroup_invite_code'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('user', 'householdgroup'), name='duplication_check_for_registration'),
        ),
    ]
