# Generated by Django 6.0.6 on 2026-07-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('householdgroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
