# Generated by Django 6.0.6 on 2026-07-23 12:58

import householdgroups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('householdgroups', '0002_householdgroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdgroup',
            name='invite_code',
            field=models.CharField(default=householdgroups.models.HouseHoldGroup.generate_invite_code, editable=False, max_length=200, unique=True),
        ),
    ]
