# Generated by Django 6.0.6 on 2026-07-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chorecards', '0003_alter_chorecard_completed_at_and_more'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.TextField()),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chorecards.chorecard')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
