# Generated by Django 6.0.6 on 2026-07-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='chore',
            new_name='choreCard',
        ),
    ]
